project_id = "iseaskggtqujanhgfxmk"

[functions.create-merchandise-payment]
verify_jwt = true

[functions.create-stream-payment]
verify_jwt = true

[functions.create-subscription-payment]
verify_jwt = true

[functions.create-tip-payment]
verify_jwt = true

[functions.generate-thumbnail]
verify_jwt = true

[functions.livepeer-stream]
verify_jwt = true

[functions.send-reset-email]
verify_jwt = false

[functions.spotify-search]
verify_jwt = true

[functions.verify-merchandise-payment]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.verify-reset-token]
verify_jwt = false

[functions.verify-subscription-payment]
verify_jwt = true

[functions.verify-tip-payment]
verify_jwt = true

[functions.gumroad-webhook]
verify_jwt = false
